apiVersion: apps/v1
kind: Deployment
metadata:
  name: homunculy
spec:
  template:
    spec:
      containers:
        - name: homunculy
          env:
            - name: DB_HOST
              value: "psql-homunculy-dev.postgres.database.azure.com"
            - name: DB_NAME
              value: "homunculy"
            - name: DB_USER
              value: "homunculy"
