apiVersion: v1
kind: Service
metadata:
  name: management-service
  labels:
    app.kubernetes.io/name: management-service
spec:
  selector:
    app.kubernetes.io/name: management-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
