apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  privatelink.server: |
    privatelink.postgres.database.azure.com:53 {
        forward . 168.63.129.16
        cache 30
    }
    postgres.database.azure.com:53 {
        forward . 168.63.129.16
        cache 30
    }
