apiVersion: v1
kind: Service
metadata:
  name: rag-service
  labels:
    app.kubernetes.io/name: rag-service
spec:
  selector:
    app.kubernetes.io/name: rag-service
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: http
