apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-client-ingress
spec:
  rules:
    - host: chat.homunculy.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-client
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homunculy-agent-ingress
spec:
  rules:
    - host: agent.homunculy.io
      http:
        paths:
          - path: /agent(?:/(.*))?
            pathType: Prefix
            backend:
              service:
                name: homunculy
                port:
                  number: 8000
