apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homunculy-apps-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Jakkapat-Chongsuwat/homunculy.git
    targetRevision: main
    path: infra/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: homunculy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
