apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../platform/coredns
  - ../../platform/homunculy/overlays/dev
  - ../../apps/homunculy/overlays/dev
  - ../../apps/management-service/overlays/dev
  - ../../apps/rag-service/overlays/dev
  - ../../apps/chat-client/overlays/dev
