apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homunculy

resources:
  - ../../base

patches:
  - path: database-config.yaml
    target:
      kind: Deployment
      name: homunculy

labels:
  - pairs:
      environment: prod
    includeSelectors: true

images:
  - name: acrhomunculyprod.azurecr.io/homunculy
    newTag: 82eb5c3e233cd5968d6f21806f67350d9c12f3f7
