apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homunculy

resources:
  - ../../base

patches:
  - path: database-config.yaml
    target:
      kind: Deployment
      name: homunculy

labels:
  - pairs:
      environment: prod
    includeSelectors: true

images:
  - name: acrhomunculyprod.azurecr.io/homunculy
    newTag: a30f43a8c6abaa8e6100370f937304d67f827471
