apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - secret-provider-class.yaml
  - network-policy.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: homunculy
  app.kubernetes.io/managed-by: kustomize
