apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homunculy

resources:
  - namespace.yaml
  - service-account.yaml
  - secret-provider-class.yaml
  - network-policy.yaml
  - ingress.yaml
  - apps/homunculy/deployment.yaml
  - apps/homunculy/service.yaml
  - apps/management-service/deployment.yaml
  - apps/management-service/service.yaml
  - apps/rag-service/deployment.yaml
  - apps/rag-service/service.yaml
  - apps/chat-client/deployment.yaml
  - apps/chat-client/service.yaml

commonLabels:
  app.kubernetes.io/part-of: homunculy
  app.kubernetes.io/managed-by: kustomize
