apiVersion: v1
kind: Service
metadata:
  name: rag-service
  labels:
    app.kubernetes.io/name: rag-service
    app.kubernetes.io/component: rag
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rag-service
